model:
  type: SequenceModel
  args: {}
dataloader:
  dataset:
    type: YawSequenceDataset
    args: {}
  batch_size: 16
optimizer:
  type: SGD
  args:
    lr: 1.e-3
scheduler:
  type: ExponentialLR
  args:
    gamma: 0.9
criterion:
  - type: MSE
    args: {}
